import type { Metadata } from 'next';

import styles from './layout.module.css';

import './globals.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <div className={styles.root}>{children}</div>
      </body>
    </html>
  );
}
